name: CI/CD Pipeline Test devdomain

on:
  push:
    branches:
      - selenium-framework

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Chrome browser
        run: |
            sudo apt-get update
            sudo apt-get install -y wget unzip libnss3 libglib2.0-0 libfontconfig1
            wget -q -O /tmp/chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i /tmp/chrome.deb || sudo apt-get -fy install

      - name: Set up ChromeDriver
        run: |
            wget -q -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$(wget -q -O - https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
            unzip /tmp/chromedriver.zip -d /tmp
            sudo mv /tmp/chromedriver /usr/local/bin/
            sudo chmod +x /usr/local/bin/chromedriver
            chromedriver --version

      - name: Run tests
        run: |
          mvn clean test
