name: CI/CD Pipeline Test for devdomain

on:
  push:
    branches:
      - selenium-framework

jobs:
  build:
    runs-on: windows-latest  # Use windows-latest for Windows environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clear Chocolatey cache
        run: choco cache clean --all

      - name: Install Google Chrome
        run: choco install googlechrome --ignore-checksums

      - name: Run tests
        run: |
          mvn clean -fae test