name: CI/CD Pipeline Test for devdomain

on:
  push:
    branches:
      - selenium-framework

jobs:
  devdomain:
    runs-on: windows-latest  # Use windows-latest for Windows environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clear Chocolatey cache
        run: choco cache clean --all

      - name: Install Google Chrome
        run: choco install googlechrome --ignore-checksums

      - name: Run tests for devdomain
        run: |
          cd devdomain
          mvn clean install -DskipTests
          mvn -fae test

      - name: Generate and Upload Artifacts for devdomain
        run: |
          mkdir -p artifacts/devdomain
          
          # Copy HTML reports from devdomain/Report (adjust path as necessary)
          if [ -d "devdomain/Report" ]; then
            cp devdomain/Report/*.html artifacts/devdomain/
          fi

      - name: Upload Artifacts for devdomain
        uses: actions/upload-artifact@v2
        with:
          name: devdomain-reports
          path: artifacts/devdomain/

  testdomain:
    runs-on: windows-latest  # Use windows-latest for Windows environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clear Chocolatey cache
        run: choco cache clean --all

      - name: Install Google Chrome
        run: choco install googlechrome --ignore-checksums

      - name: Run tests for testdomain
        run: |
          cd testdomain
          mvn clean install -DskipTests
          mvn -fae test

      - name: Generate and Upload Artifacts for testdomain
        run: |
          mkdir -p artifacts/testdomain
          
          # Copy HTML reports from testdomain/Report (adjust path as necessary)
          if [ -d "testdomain/Report" ]; then
            cp testdomain/Report/*.html artifacts/testdomain/
          fi

      - name: Upload Artifacts for testdomain
        uses: actions/upload-artifact@v2
        with:
          name: testdomain-reports
          path: artifacts/testdomain/
