name: CI/CD Pipeline Test for devdomain

on:
  push:
    branches:
      - selenium-framework

jobs:
  build:
    runs-on: windows-latest  # Use windows-latest for Windows environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Chrome browser
        run: |
          choco install googlechrome --confirm  # Install Chrome using Chocolatey package manager
          refreshenv  # Refresh environment variables to include newly installed software

      - name: Set up ChromeDriver
        run: |
          choco install chromedriver --confirm  # Install ChromeDriver using Chocolatey
          refreshenv  # Refresh environment variables to include newly installed software
          chromedriver --version  # Verify ChromeDriver installation

      - name: Run tests
        run: |
          mvn clean test