name: CI/CD Pipeline Test for devdomain

on:
  workflow_dispatch: 
  # push:
  #   branches:
  #     - selenium-framework

jobs:
  devdomain:
    runs-on: windows-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clear Chocolatey cache
        run: choco cache clean --all

      - name: Install Google Chrome
        run: choco install googlechrome --ignore-checksums

      - name: Run tests for devdomain
        run: |
          mvn clean install -DskipTests
          cd devdomain
          mvn -fae test

      - name: Generate and Upload Artifacts for devdomain
        run: |
          mkdir -p artifacts/devdomain
          
          # Copy HTML reports from devdomain/Report (adjust path as necessary)
          if (Test-Path "devdomain/Report") {
            Copy-Item -Path "devdomain/Report/*.html" -Destination "artifacts/devdomain/"
          }

      - name: Upload Artifacts for devdomain
        uses: actions/upload-artifact@v4
        with:
          name: devdomain-reports
          path: artifacts/devdomain/

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: devdomain Test Report
          to: akshay.sawant@apptware.com,kunal.kankriya@apptware.com
          from: Testing Team
          body: Please find attachment of devdomain test report
          attachments: artifacts/devdomain/*

  testdomain:
    runs-on: windows-latest  
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clear Chocolatey cache
        run: choco cache clean --all

      - name: Install Google Chrome
        run: choco install googlechrome --ignore-checksums

      - name: Run tests for testdomain
        run: |
          mvn clean install -DskipTests
          cd testdomain
          mvn -fae test

      - name: Generate and Upload Artifacts for testdomain
        run: |
          mkdir -p artifacts/testdomain
          
          # Copy HTML reports from testdomain/Report (adjust path as necessary)
          if (Test-Path "testdomain/Report") {
            Copy-Item -Path "testdomain/Report/*.html" -Destination "artifacts/testdomain/"
          }

      - name: Upload Artifacts for testdomain
        uses: actions/upload-artifact@v4
        with:
          name: testdomain-reports
          path: artifacts/testdomain/
      
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: testdomain Test Report
          to: akshay.sawant@apptware.com,kunal.kankriya@apptware.com
          from: Testing Team
          body: Please find attachment of testdomain test report
          attachments: artifacts/testdomain/*
